language: node_js
node_js:
- '8'
- '12'
services:
- rabbitmq-server
deploy:
  provider: npm
  email: clysuva@gmail.com
  api_key:
    secure: DSyprbG84PM5yeVgYJwf/XLrizbgixmSeIPYvO8YROqhdcG+CXt+k2i9Nc58Oogb5G39BFyamfDP81cdjEbiDU7d9TB5JD1S+eyPlswh1CZrawkwyfGNA8sLPgV4P8f6EQpSuenrDbY46grx8Scp11mOh5516mlfP8fYLyv2XngX1ccje2ln/ar97VTHhL+4smW38PGq0/eZMBFZw/OMIygow7saS5fSUKS3HkzxFs4eFQ3IX8UpV8Ym59TivSOhO7SelO2CI8HHt9xnJ1c8uLvJOjx45500t2tKBRx33rd/uefOtWd335uuoIn1kHM0EhSWdmL8+RAOcaTBcWaVh2NuIG3eJTmpq2FdDHuuPtVhCpjEQgElHR47G1SBIccfmn/FCPaa8djYwe4dTRW8Ldb+7+24DmdVVL49vUz8E3B8seTYr8HH8gPvLo3Mw1m5KBIDkDQS0WkRW8BX3S19LGhrzyUvQEGyWb3IWkI2pQqlum82H05TxNili7B+xndZsDH0sBPjGLtzdasvQ356Jx3+dnSFLtSqPHck2+zHCkojZLpRqB47hYcEfDHjGpQ3Oi9HEbMqDmy9W40R/ecJSA26Us3pTDy9xzLpdtRKMxj1f+QAKBL7knhYko6OG6hSkOSRGIXm/2n9hjAx+CbEsc2lUuDiiIu/TQO77t8gP0g=
  on:
    branch: master
    repo: esticade/esticade.js
